# Config for Dependabot updates. See Documentation here:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat(dep)"

  # Enable version updates for Docker
  # We need to specify each Dockerfile in a separate entry because Dependabot doesn't
  # support wildcards or recursively checking subdirectories. Check this issue for updates:
  # https://github.com/dependabot/dependabot-core/issues/2178
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the directory
    directory: "compose/local/django/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat(dep)"

  - package-ecosystem: "docker"
    directory: "compose/local/docs/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat(dep)"

  - package-ecosystem: "docker"
    directory: "compose/local/node/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat(dep)"

  - package-ecosystem: "docker"
    directory: "compose/production/aws/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat(dep)"

  - package-ecosystem: "docker"
    directory: "compose/production/django/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat(dep)"

  - package-ecosystem: "docker"
    directory: "compose/production/postgres/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat(dep)"

  - package-ecosystem: "docker"
    directory: "compose/production/traefik/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat(dep)"

  # Enable version updates for Python/Pip - Production
  - package-ecosystem: "pip"
    # Look for a `requirements.txt` in the `root` directory
    # also 'setup.cfg', 'runtime.txt' and 'requirements/*.txt'
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat(dep)"
