version: "3"

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_redis: {}
  production_data:
    driver: local
    driver_opts:
      type: none
      device: /var/www/apps.ikim.uk-essen.de/public/app/sars_dashboard/protected
      o: bind
  production_static:
    driver: local
    driver_opts:
      type: none
      device: /var/www/apps.ikim.uk-essen.de/public/static
      o: bind


services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: dashboard_production_django
    user: "0"
    depends_on:
      - postgres
      - redis
    volumes:
      - production_static:/app/staticfiles:z
      - production_data:/app/sars_dashboard/protected:z
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    ports:
      - "5000"
    labels:
      kompose.image-pull-policy: "Never"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: dashboard_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
    ports:
      - "5432"
    labels:
      kompose.image-pull-policy: "Never"

  redis:
    image: redis:6
    volumes:
      - production_redis:/data:z
    ports:
      - "6379"

  celeryworker:
    <<: *django
    image: dashboard_production_celeryworker
    command: /start-celeryworker
    labels:
      kompose.image-pull-policy: "Never"

  celerybeat:
    <<: *django
    image: dashboard_production_celerybeat
    command: /start-celerybeat
    labels:
      kompose.image-pull-policy: "Never"

  flower:
    <<: *django
    image: dashboard_production_flower
    command: /start-flower
    labels:
      kompose.image-pull-policy: "Never"

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: dashboard_production_nginx
    depends_on:
      - django
    volumes:
      - production_static:/static:z
      - production_data:/app/sars_dashboard/protected:z
    ports:
      - "0.0.0.0:8080:80"
      - "0.0.0.0:5555:5555"
    labels:
      kompose.image-pull-policy: "Never"
