version: "3"

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_redis: {}
  production_static: {}
  production_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: sars_dashboard_production_django
    user: root
    depends_on:
      - postgres
      - redis
    volumes:
      - production_static:/app/staticfiles:z
      - production_data:/app/sars_dashboard/protected:z
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sars_dashboard_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres


  redis:
    image: redis:6
    volumes:
      - production_redis:/data:z

  celeryworker:
    <<: *django
    image: sars_dashboard_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: sars_dashboard_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: sars_dashboard_production_flower
    command: /start-flower

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: sars_dashboard_production_nginx
    depends_on:
      - django
    volumes:
      - production_static:/static:z
      - production_data:/app/sars_dashboard/protected:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:5555:5555"
