# Generated by Django 3.2.10 on 2022-01-05 18:04

from django.db import migrations, models
import django.db.models.deletion
import sars_dashboard.calls.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='samples.sample', verbose_name='Call')),
            ],
        ),
        migrations.CreateModel(
            name='PangolinCall',
            fields=[
                ('call_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calls.call')),
                ('taxon', models.CharField(max_length=100)),
                ('lineage', models.CharField(max_length=100)),
                ('conflict', models.CharField(max_length=100)),
                ('ambiguity_score', sars_dashboard.calls.models.MinMaxFloat()),
                ('scorpio_call', models.CharField(max_length=100)),
                ('scorpio_support', sars_dashboard.calls.models.MinMaxFloat()),
                ('scorpio_conflict', sars_dashboard.calls.models.MinMaxFloat()),
                ('version', models.CharField(max_length=100)),
                ('pangolin_version', models.CharField(max_length=100)),
                ('pangoLEARN_version', models.CharField(max_length=100)),
                ('pango_version', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            bases=('calls.call',),
        ),
    ]
